### PR TITLE
New sponsor and online clarification

### PR DESCRIPTION
**Pull request by veekaybee**
+ New individual sponsor
+ Clarification that all talks will be recorded

@roycoding

### CODE REVIEW

**Review by EconoBen — CHANGES_REQUESTED** [review]
W&B Looks good. Mahdi looks good but I'm getting a broken link which is flubbing the look.

Also for "All Talks will be Recorded and shared!" imo. the lowercase "s" in shared change the aesthetic. 

What if we did "100% Online", added more spacing underneath, then in a smaller font size "(All Talks will be Recorded Shared!)"

Screen Shot 2022-10-10 at 06 29 58

**Comment by veekaybee** [comment]
>getting a broken link

locally? working for me but I wonder if github is just not rendering it
Screen Shot 2022-10-10 at 10 02 27 AM

>What if we did "100% Online", added more spacing underneath, then in a smaller font size "(All Talks will be Recorded and Shared!)"
How's this? 
Screen Shot 2022-10-10 at 10 04 48 AM

**Review by EconoBen — APPROVED** [review]
I like this so much more!

**Comment by roycoding** [comment]
@veekaybee I don't think you added Mahdi's pic to the commit

**Pull request merged**
